### ISSUE TITLE
Front, reverse order (arrange by PublishDate)

### ISSUE THREAD

**Issue by jorgenskogmo** [tobaccoplaybook/site#5]
On the index pages, we want the arguments to be sorted so that the newest one(s) are at the top.

**Comment by tobaccoplaybook-editor** [comment]
Added sort function (using https://github.com/Teun/thenBy.js ), so that arguments are  
- sorted by publicDate (from their frontmatter)  
- and then by argumentId

This means arranges the arguments-list in reverse chronological order,  and if there is multiple arguments published on the same date, they are ordered by their argumentId in increasing order.

**Comment by jorgenskogmo** [comment]
Added sort function (using https://github.com/Teun/thenBy.js ), so that arguments are

- sorted by publicDate (from their frontmatter)  
- and then by argumentId  

This means arranges the arguments-list in reverse chronological order, and if there is multiple arguments published on the same date, they are ordered by their argumentId in increasing order.

**Comment by jorgenskogmo** [comment]
Published as '170310 09:30 update' 
v0.9.24
